added methods validation
la-true-liga/mercatech-express-api pull request #26
Opened 2023-11-10 18:18 UTC by jdomingu98

2023-11-10 18:29 UTC, AlexTrujillo2002 approved these changes
añadiendo cositas muy bien

2023-11-10 18:29 UTC, 42Alberto commented
Sa

2023-11-10 18:30 UTC, 42Alberto approved these changes
De locos "Mandado desde un iPhone 15 pro max

2023-11-10 18:33 UTC, ruzafa8 approved these changes

2023-11-10 18:34 UTC, ruzafa8 requested changes
Falta la paginación

2023-11-10 18:59 UTC, 42Alberto approved these changes
Mu bien *Mandado desde un iPhone 16 Pro X*

2023-11-12 00:34 UTC, ruzafa8 commented on src/controllers/item.controller.ts
> +    const { page } = req.params;
Es **req.params** o **req.query**?

Los parámetros son los que van después del "?" `/items?category=FRUITS&page=3`, creo que con ese **req.params** iría así `/items/3?category=FRUITS`. Quizás baste con mover esta variable a la línea 42.

2023-11-12 00:35 UTC, ruzafa8 commented on src/controllers/item.controller.ts
> +        if (page === undefined)
Este if está bien? No tiene nada en el cuerpo :(

2023-11-12 00:42 UTC, ruzafa8 approved these changes

2023-11-12 00:42 UTC, ruzafa8 commented on src/controllers/item.controller.ts
> +        if (id == undefined)
```suggestion
        if (id === undefined)
```

2023-11-12 00:42 UTC, ruzafa8 commented on src/controllers/item.controller.ts
> +    const {name, category} = req.query;
Es **req.params** o **req.query**?

Los parámetros son los que van después del "?" `/items?category=FRUITS&page=3`, creo que con ese **req.params** iría así `/items/3?category=FRUITS`. Quizás baste con mover esta variable a la línea 42.
```suggestion
    const { name, category, page } = req.query;
```

2023-11-15 12:33 UTC, ruzafa8 commented
Ahora si me gusta muchísimo :D

2023-11-24 16:59 UTC, merged